<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Drupal\kibo_sdk_proxy\Mozu\Api\Resources\Commerce\Customer;

use Drupal\kibo_sdk_proxy\Mozu\Api\Clients\Commerce\Customer\AddressValidationRequestClient;
use Drupal\kibo_sdk_proxy\Mozu\Api\ApiContext;


/**
* Use the Address Validation resource to validate addresses associated with a customer account contact.
*/
class AddressValidationRequestResource {

		private $apiContext;
			
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	



	/**
	* Validates the customer address supplied in the request.
	*
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @param AddressValidationRequest $addressValidationRequest Properties of the address used for validation of the account's full address. This content may include multiple lines of an address, city, state/province, zip/postal code, and country.
	* @return AddressValidationResponse 
	* @deprecated deprecated since version 1.17
	*/
	public function validateAddress($addressValidationRequest, $responseFields =  null)
	{
		$mozuClient = AddressValidationRequestClient::validateAddressClient($addressValidationRequest, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* Validates the customer address supplied in the request.
	*
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\MozuResult. errorFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\ApiException
	*/
	public function validateAddressAsync($addressValidationRequest, $responseFields =  null)
	{
		$mozuClient = AddressValidationRequestClient::validateAddressClient($addressValidationRequest, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

