<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Drupal\kibo_sdk_proxy\Mozu\Api\Resources\Platform\Appdev;

use Drupal\kibo_sdk_proxy\Mozu\Api\Clients\Platform\Appdev\PackageClient;
use Drupal\kibo_sdk_proxy\Mozu\Api\ApiContext;


/**
* This resource is not public.
*/
class PackageResource {

				



	/**
	* This operation is not public.
	*
	* @param string $applicationKey The application key uniquely identifies the developer namespace, application ID, version, and package in Dev Center. The format is {Dev Account namespace}.{Application ID}.{Application Version}.{Package name}. 
	* @param string $fileName 
	* @return Stream 
	* @deprecated deprecated since version 1.17
	*/
	public function getFile($applicationKey, $fileName)
	{
		$mozuClient = PackageClient::getFileClient($applicationKey, $fileName);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* This operation is not public.
	*
	* @param string $applicationKey The application key uniquely identifies the developer namespace, application ID, version, and package in Dev Center. The format is {Dev Account namespace}.{Application ID}.{Application Version}.{Package name}. 
	* @param string $fileName 
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\MozuResult. errorFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\ApiException
	*/
	public function getFileAsync($applicationKey, $fileName)
	{
		$mozuClient = PackageClient::getFileClient($applicationKey, $fileName);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

