<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Drupal\kibo_sdk_proxy\Mozu\Api\Resources\Commerce\Orders;

use Drupal\kibo_sdk_proxy\Mozu\Api\Clients\Commerce\Orders\OrderValidationResultClient;
use Drupal\kibo_sdk_proxy\Mozu\Api\ApiContext;


/**
* Manage the results of order validation.
*/
class OrderValidationResultResource {

		private $apiContext;
			
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	



	/**
	* Retrieves a list of the validation results associated with the order.
	*
	* @param string $orderId Unique identifier of the order.
	* @return array|OrderValidationResult 
	* @deprecated deprecated since version 1.17
	*/
	public function getValidationResults($orderId)
	{
		$mozuClient = OrderValidationResultClient::getValidationResultsClient($orderId);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* Retrieves a list of the validation results associated with the order.
	*
	* @param string $orderId Unique identifier of the order.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\MozuResult. errorFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\ApiException
	*/
	public function getValidationResultsAsync($orderId)
	{
		$mozuClient = OrderValidationResultClient::getValidationResultsClient($orderId);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* Add a new order validation result to a submitted order.
	*
	* @param string $orderId Unique identifier of the order.
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @param OrderValidationResult $validationResult Properties of the resulting order validation performed by an order validation capability.
	* @return OrderValidationResult 
	* @deprecated deprecated since version 1.17
	*/
	public function addValidationResult($validationResult, $orderId, $responseFields =  null)
	{
		$mozuClient = OrderValidationResultClient::addValidationResultClient($validationResult, $orderId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* Add a new order validation result to a submitted order.
	*
	* @param string $orderId Unique identifier of the order.
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\MozuResult. errorFn is passed Drupal\kibo_sdk_proxy\Mozu\Api\ApiException
	*/
	public function addValidationResultAsync($validationResult, $orderId, $responseFields =  null)
	{
		$mozuClient = OrderValidationResultClient::addValidationResultClient($validationResult, $orderId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

