<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\acf_kibo\Mozu\Api\Urls\Platform\Extensions;

use Drupal\acf_kibo\Mozu\Api\MozuUrl;
use Drupal\acf_kibo\Mozu\Api\UrlLocation;

class CredentialStoreEntryUrl  {

	/**
		* Get Resource Url for StoreCredentials
		* @return string Resource Url
	*/
	public static function storeCredentialsUrl()
	{
		$url = "/api/platform/extensions/credentialStore/";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		return $mozuUrl;
	}
	
}

?>

