<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\acf_kibo\Mozu\Api\Contracts\InstalledApplications;



/**
*	Mozu.InstalledApplications.Contracts.ExtensionConfiguration ApiType DOCUMENT_HERE 
*/
class ExtensionConfiguration
{
	/**
	*The Arc.js application key.
	*/
	public $applicationKey;

	/**
	*Custom application-level settings specified as key-value pairs.
	*/
	public $configuration;

}

?>
