export const ACF_STORE_NAME = 'acfStore'
export const ACF_PATH_DRUPAL_API = window.location.origin + '/api/'
export const KIBO_PATH_DRUPAL_API = window.location.origin + '/kibo_api/'
export const ACF_PATH_CART = '/cart'
export const ACF_PATH_CHECKOUT = '/checkout'
export const ACF_ID_ADD_TO_CART = 'acf_blocks_add_to_cart'
export const ACF_ID_FULL_CART = 'acf_blocks_full_cart'
export const ACF_ID_MINI_CART = 'acf_blocks_mini_cart'

//Reminder
//_SUCCESS and _FAIL is part of the redux-axios-middleware scheme

export const types = {
  GET_CURRENT_CART: 'GET_CURRENT_CART',
  GET_CURRENT_CART_SUCCESS: 'GET_CURRENT_CART_SUCCESS',
  GET_CURRENT_CART_FAIL: 'GET_CURRENT_CART_FAIL',

  UPDATE_CART: 'UPDATE_CART',
  UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
  UPDATE_CART_FAIL: 'UPDATE_CART',

  DELETE_CART: 'DELETE_CART',
  DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
  DELETE_CART_FAIL: 'DELETE_CART_FAIL',

  GET_CART_ITEM: 'GET_CART_ITEM',
  GET_CART_ITEM_SUCCESS: 'GET_CART_ITEM_SUCCESS',
  GET_CART_ITEM_FAIL: 'GET_CART_ITEM_FAIL',

  ADD_CART_ITEM: 'ADD_CART_ITEM',
  ADD_CART_ITEM_SUCCESS: 'ADD_CART_ITEM_SUCCESS',
  ADD_CART_ITEM_FAIL: 'ADD_CART_ITEM_FAIL',

  UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
  UPDATE_CART_ITEM_SUCCESS: 'UPDATE_CART_ITEM_SUCCESS',
  UPDATE_CART_ITEM_FAIL: 'UPDATE_CART_ITEM_FAIL',

  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
  REMOVE_CART_ITEM_FAIL: 'REMOVE_CART_ITEM_FAIL',

  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',

  FETCH_PRODUCT: 'FETCH_PRODUCT',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCT_FAIL: 'FETCH_PRODUCT_FAIL',

  CREATE_ANON_AUTH_TICKET: 'CREATE_ANON_AUTH_TICKET',
  CREATE_ANON_AUTH_TICKET_SUCCESS: 'CREATE_ANON_AUTH_TICKET_SUCCESS',
  CREATE_ANON_AUTH_TICKET_FAIL: 'CREATE_ANON_AUTH_TICKET_FAIL',
}
