<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\acf_kibo\Mozu\Api\Contracts\CommerceRuntime\Payments;



/**
*	Mozu.CommerceRuntime.Contracts.Payments.CheckPayment ApiType DOCUMENT_HERE 
*/
class CheckPayment
{
	/**
	*If applicable, the check number associated with the payment action or interaction.
	*/
	public $checkNumber;

}

?>
