<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\kibo_sdk_proxy\Mozu\Api\Urls\Platform;

use Drupal\kibo_sdk_proxy\Mozu\Api\MozuUrl;
use Drupal\kibo_sdk_proxy\Mozu\Api\UrlLocation;

class TenantUrl  {

	/**
		* Get Resource Url for GetTenant
		* @param string $responseFields Use this field to include those fields which are not included by default.
		* @param int $tenantId Unique identifier of the Mozu tenant.
		* @return string Resource Url
	*/
	public static function getTenantUrl($responseFields, $tenantId)
	{
		$url = "/api/platform/tenants/{tenantId}?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::HOME_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		$url = $mozuUrl->formatUrl("tenantId", $tenantId);
		return $mozuUrl;
	}
	
}

?>

