<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\acf_kibo\Mozu\Api\Contracts\PaymentService;



/**
*	Properties of the credential fields associated with the payment gateway.
*/
class GatewayCredentialFieldDefinition
{
	/**
	*The sequential display order of the gateway in .
	*/
	public $adminDisplayOrder;

	/**
	*The name that displays for the payment gateway or third-party credentials field. 
	*/
	public $displayName;

	/**
	*The user supplied name that appears in . You can use this field for identification purposes.
	*/
	public $name;

	/**
	*The name of the Volusion store.
	*/
	public $volusionStoreName;

}

?>
