<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\acf_kibo\Mozu\Api\Contracts\ProductAdmin;



/**
*	The site category to which a product belongs.
*/
class ProductCategory
{
	/**
	*Unique identifier for the storefront container used to organize products.
	*/
	public $categoryId;

}

?>
