<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Drupal\acf_kibo\Mozu\Api\Contracts\ProductAdmin;



/**
*	The targeted shipping zone for the product.
*/
class TargetedShippingZone
{
	/**
	*The zone string for the tenant domain.
	*/
	public $zone;

}

?>
